id: type_safety_quiz
learningObjectives:
  - Assess understanding of TypeScript's type safety.
hints:
  - Think about the type mismatch. Which line tries to assign a string to a
    number variable?
  - "Check TypeScript's type rules:
    [help](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html)."
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Let's put your new type knowledge to the test! Which of the following
              examples will cause a compilation error?
          - text: "`let age: number = 25; age = '26';`"
          - text: "`let isChecked: boolean = true; isChecked = false;`"
          - text: "`let name: string = 'Lucca'; name = 'John';`"
    - actionId: quiz_message
      name: quiz
      params:
        person: lucca
        options:
          - "`let age: number = 25; age = '26';`"
          - "`let isChecked: boolean = true; isChecked = false;`"
          - "`let name: string = 'Lucca'; name = 'John';`"
trigger:
  type: chat_form_submitted
  flowNode:
    switch:
      key: ${formSubmission}
      cases:
        A:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Correct! Changing `age` from a number to a string violates the type
                      restriction!
            - actionId: finish_step
        B:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Not quite. Boolean to boolean is perfectly valid. Try another choice.
            - actionId: replay_action
              params:
                actionName: quiz
        C:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: That works just fine—you're assigning strings here, which is allowed. Give
                      another option a go!
            - actionId: replay_action
              params:
                actionName: quiz
